# Generated by Django 5.0.7 on 2024-07-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('amount_of_money', models.IntegerField(default=10000)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name_character', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('patronus', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=1908)),
                ('xp_points', models.PositiveIntegerField(default=6)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_cards', to='cards.user')),
                ('previous_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_cards', to='cards.user')),
            ],
        ),
    ]
